name: "PHPUnit"


on:
    pull_request:
#        paths:
#            - "**.php"
#            - "phpunit.xml.dist"
#            - ".github/workflows/phpunit.yaml"
    push:
#        paths:
#            - "**.php"
#            - "phpunit.xml.dist"
#            - ".github/workflows/phpunit.yaml"

jobs:
    unit-tests:
        name: PHPUnit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.2', '8.3']
        steps:
            - uses: actions/checkout@master

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --ignore-platform-req="ext-*" ${{ matrix.composer-prefer }}

            -   name: Run test suite
                run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}
